# Maximum width of each line
max_width = 100

# Use spaces for indentation
hard_tabs = false
tab_spaces = 4

# Formatting of imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
imports_layout = "HorizontalVertical"

# Formatting of comments
wrap_comments = true
comment_width = 100
normalize_comments = true

# Function and expression formatting
fn_args_layout = "Tall"
fn_single_line = false
where_single_line = false
overflow_delimited_expr = true
struct_lit_single_line = true
struct_variant_width = 40

# Control flow formatting
control_brace_style = "AlwaysSameLine"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# Chain formatting
chain_width = 60
use_small_heuristics = "Max"
use_try_shorthand = true

# Misc formatting
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_impl_items = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
edition = "2021"

# Documentation formatting
doc_comment_code_block_width = 100
doc_comment_code_block_target = "All"

# Error handling
error_on_line_overflow = true
error_on_unformatted = true

# Unstable features (requires nightly)
unstable_features = true
version = "Two"
combine_control_expr = true
condense_wildcard_suffixes = true
format_args = true
format_args_capture = true
format_generated_files = true
format_generated_identifiers = true
hex_literal_case = "Upper"
normalize_doc_attributes = true
overflow_delimited_match_arm = true
skip_children = false
space_after_colon = true
spaces_around_ranges = false
struct_field_align_threshold = 0
