[build]
target = "aarch64-unknown-none"
rustflags = [
    "-C",
    "link-arg=--script=kernel/src/arch/aarch64/linker.ld",
    "-C",
    "target-cpu=generic",
    "-C",
    "force-frame-pointers=yes",
]

[target.aarch64-unknown-none]
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a72 -smp 4 -m 4G -nographic -kernel"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "abort"
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.test]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "abort"
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[alias]
kbuild = "build --target aarch64-unknown-none"
kcheck = "check --target aarch64-unknown-none"
ktest = "test --target aarch64-unknown-none"
kclippy = "clippy --target aarch64-unknown-none -- -D warnings"
kfmt = "fmt --all"
kdoc = "doc --no-deps --target aarch64-unknown-none"
krun = "run --target aarch64-unknown-none"
krelease = "build --target aarch64-unknown-none --release"
